# Generated by Django 4.0.3 on 2022-07-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='author',
            new_name='author_id',
        ),
    ]
