# Generated by Django 4.0.3 on 2022-08-31 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
        ('story_app', '0003_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsFollowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_followed', models.DateField(default=django.utils.timezone.now)),
                ('author_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='taggit.tag')),
            ],
        ),
    ]
