# Generated by Django 4.0.3 on 2022-09-03 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story_app', '0011_alter_story_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_date', models.DateField(default=django.utils.timezone.now)),
                ('story', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='story_app.story')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='CollectedStory',
            new_name='ListedStory',
        ),
        migrations.RenameModel(
            old_name='Collection',
            new_name='StoryList',
        ),
        migrations.RenameField(
            model_name='listedstory',
            old_name='story_id',
            new_name='story',
        ),
        migrations.RenameField(
            model_name='storylist',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='tagsfollowed',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='tagsfollowed',
            old_name='author_id',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
