# Generated by Django 4.0.3 on 2022-09-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0015_rename_owner_storylist_user_storylist_stories_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListedStory',
        ),
    ]
