# Generated by Django 4.0.3 on 2022-09-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0016_delete_listedstory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storylist',
            options={'ordering': ['created_date']},
        ),
        migrations.AddField(
            model_name='storylist',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='slug'),
        ),
    ]
