# Generated by Django 4.0.3 on 2022-09-05 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story_app', '0017_alter_storylist_options_storylist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='author_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
