# Generated by Django 4.0.3 on 2022-09-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0019_alter_editsuggestion_story_id_alter_likedstory_story_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
