# Generated by Django 4.0.3 on 2022-09-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0020_story_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='view_count',
        ),
    ]
