# Generated by Django 4.0.3 on 2022-09-12 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story_app', '0021_remove_story_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='storylist',
            name='pinners',
            field=models.ManyToManyField(related_name='pinned_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
