# Generated by Django 4.0.3 on 2022-09-16 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0024_story_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editsuggestion',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='likedstory',
            name='liked_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='story',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='storylist',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tagsfollowed',
            name='date_followed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='updatedstory',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
