# Generated by Django 4.0.3 on 2022-09-19 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story_app', '0026_story_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='storylist',
            name='pinner_count',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='storylist',
            name='pinners',
            field=models.ManyToManyField(blank=True, related_name='pinned_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
