# Generated by Django 4.0.3 on 2022-09-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0031_rename_follower_tagsfollowed_follower_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagsfollowed',
            old_name='date_followed',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='tagsfollowed',
            name='description',
            field=models.CharField(default='', max_length=12000),
        ),
        migrations.AddField(
            model_name='tagsfollowed',
            name='story_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
