# Generated by Django 4.0.3 on 2022-09-22 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('story_app', '0032_rename_date_followed_tagsfollowed_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsExtra',
            fields=[
                ('tag', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='taggit.tag')),
                ('follower_count', models.BigIntegerField(default='0')),
                ('story_count', models.BigIntegerField(default='0')),
                ('description', models.CharField(default='', max_length=300)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='TagsFollowed',
        ),
    ]
