# Generated by Django 4.0.3 on 2022-09-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0036_alter_story_content_alter_story_content_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(default='Title', max_length=300),
        ),
    ]
