# Generated by Django 4.0.3 on 2022-09-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0039_alter_storylist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover_image',
            field=models.ImageField(default='', upload_to='story_images'),
        ),
    ]
