# Generated by Django 4.0.3 on 2022-09-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_app', '0003_userextra'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower_id', 'following_id'), name='unique_follow'),
        ),
        migrations.AlterModelTable(
            name='follow',
            table='follow',
        ),
    ]
