# Generated by Django 4.0.3 on 2022-09-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('author_app', '0011_alter_userextra_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='following_tags',
            field=models.ManyToManyField(to='taggit.tag'),
        ),
    ]
