# Generated by Django 4.0.3 on 2022-09-08 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
        ('story_app', '0019_alter_editsuggestion_story_id_alter_likedstory_story_and_more'),
        ('author_app', '0013_alter_userextra_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='cover_image',
            field=models.ImageField(default='static/svg/profile-icon.svg', upload_to='static/media/author_images'),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='followers',
            field=models.ManyToManyField(null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='following',
            field=models.ManyToManyField(null=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='following_tags',
            field=models.ManyToManyField(null=True, to='taggit.tag'),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='stories',
            field=models.ManyToManyField(null=True, to='story_app.story'),
        ),
    ]
