# Generated by Django 4.0.3 on 2022-09-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0022_storylist_pinners'),
        ('author_app', '0015_alter_userextra_followers_alter_userextra_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='pinned_lists',
            field=models.ManyToManyField(to='story_app.storylist'),
        ),
    ]
