# Generated by Django 4.0.3 on 2022-09-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author_app', '0016_userextra_pinned_lists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextra',
            name='pinned_lists',
        ),
    ]
