# Generated by Django 4.0.3 on 2022-09-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0022_storylist_pinners'),
        ('author_app', '0017_remove_userextra_pinned_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='lists',
            field=models.ManyToManyField(to='story_app.storylist'),
        ),
    ]
