# Generated by Django 4.0.3 on 2022-09-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_app', '0018_userextra_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='follower_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
