# Generated by Django 4.0.3 on 2022-09-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0027_storylist_pinner_count_alter_storylist_pinners'),
        ('author_app', '0021_userextra_following_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='pinned_lists',
            field=models.ManyToManyField(related_name='pinned_lists', to='story_app.storylist'),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='lists',
            field=models.ManyToManyField(related_name='created_lists', to='story_app.storylist'),
        ),
    ]
