# Generated by Django 4.0.3 on 2022-09-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_app', '0025_alter_userextra_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='cover_image',
            field=models.ImageField(default='media/author_images/default.jpg', upload_to='author_images'),
        ),
    ]
