# Generated by Django 4.0.3 on 2022-09-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('story_app', '0040_alter_story_cover_image'),
        ('author_app', '0026_alter_userextra_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='lists',
            field=models.ManyToManyField(blank=True, related_name='created_lists', to='story_app.storylist'),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='pinned_lists',
            field=models.ManyToManyField(blank=True, related_name='pinned_lists', to='story_app.storylist'),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='stories',
            field=models.ManyToManyField(blank=True, to='story_app.story'),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='tags',
            field=models.ManyToManyField(blank=True, to='taggit.tag'),
        ),
    ]
