# Generated by Django 4.0.3 on 2022-07-04 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=300)),
                ('content', models.CharField(default='story', max_length=12000)),
                ('editable', models.BooleanField(default=False)),
                ('updated', models.BooleanField(default=False)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='UpdatedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_title', models.CharField(default='new title', max_length=300)),
                ('new_content', models.CharField(default='new content', max_length=12000)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('og_story_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='story_app.story')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('reader_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='story_app.story')),
            ],
        ),
        migrations.CreateModel(
            name='EditSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_removed', models.CharField(default='content removed', max_length=12000)),
                ('content_added', models.CharField(default='content added', max_length=12000)),
                ('comments', models.CharField(default='comments', max_length=12000)),
                ('liked', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('editor_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='story_app.story')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='list Name', max_length=300)),
                ('description', models.CharField(default='List Description', max_length=1200)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('owner_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('parent_list', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='story_app.collection')),
                ('story_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='story_app.story')),
            ],
        ),
    ]
