# Generated by Django 4.0.3 on 2022-08-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0004_tagsfollowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
