# Generated by Django 4.0.3 on 2022-09-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0006_alter_story_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='cover_image',
            field=models.ImageField(default='none', upload_to='media'),
        ),
    ]
