# Generated by Django 4.0.3 on 2022-09-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0010_alter_story_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover_image',
            field=models.ImageField(default='none', upload_to='static/media/story_images'),
        ),
    ]
