# Generated by Django 4.0.3 on 2022-09-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0014_alter_storylist_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storylist',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='storylist',
            name='stories',
            field=models.ManyToManyField(to='story_app.story'),
        ),
        migrations.AlterField(
            model_name='storylist',
            name='description',
            field=models.CharField(default='list description', max_length=1200),
        ),
        migrations.AlterField(
            model_name='storylist',
            name='name',
            field=models.CharField(default='list name', max_length=300),
        ),
    ]
