# Generated by Django 4.0.3 on 2022-09-08 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('story_app', '0018_alter_story_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editsuggestion',
            name='story_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='story_app.story'),
        ),
        migrations.AlterField(
            model_name='likedstory',
            name='story',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='story_app.story'),
        ),
        migrations.AlterField(
            model_name='readinghistory',
            name='story_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='story_app.story'),
        ),
        migrations.AlterField(
            model_name='tagsfollowed',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taggit.tag'),
        ),
        migrations.AlterField(
            model_name='updatedstory',
            name='og_story_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='story_app.story'),
        ),
    ]
