# Generated by Django 4.0.3 on 2022-09-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0022_storylist_pinners'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadingHistory',
        ),
    ]
