# Generated by Django 4.0.3 on 2022-09-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0025_alter_editsuggestion_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='like_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
