# Generated by Django 4.0.3 on 2022-09-20 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('story_app', '0028_remove_tagsfollowed_user_tagsfollowed_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsfollowed',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tagsfollowed',
            name='user',
        ),
        migrations.AddField(
            model_name='tagsfollowed',
            name='followers',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='tagsfollowed',
            name='tag',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='taggit.tag'),
        ),
    ]
