# Generated by Django 4.0.3 on 2022-09-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0033_tagsextra_delete_tagsfollowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(default='story', max_length=12000),
        ),
    ]
