# Generated by Django 4.0.3 on 2022-09-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0034_alter_story_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='content_html',
            field=models.TextField(default='Tell your story.', editable=False),
        ),
    ]
