# Generated by Django 4.0.3 on 2022-09-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0035_story_content_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(default='Tell your story.', max_length=12000),
        ),
        migrations.AlterField(
            model_name='story',
            name='content_html',
            field=models.TextField(default='', editable=False),
        ),
    ]
