# Generated by Django 4.0.3 on 2022-09-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0037_alter_story_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.TextField(default='Title', max_length=300),
        ),
    ]
