# Generated by Django 4.0.3 on 2022-09-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0038_alter_story_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storylist',
            name='description',
            field=models.TextField(default='list description', max_length=1200),
        ),
    ]
