# Generated by Django 4.1.1 on 2022-10-07 15:52

from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0041_alter_story_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(default='Tell your story.', max_length=12000),
        ),
        migrations.AlterField(
            model_name='story',
            name='content_html',
            field=django_bleach.models.BleachField(default='', editable=False),
        ),
    ]
