# Generated by Django 4.1.1 on 2022-10-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0043_story_content_minified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content_html',
            field=models.TextField(default='', editable=False),
        ),
    ]
