# Generated by Django 4.1.1 on 2022-10-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0045_alter_story_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content_html',
            field=models.TextField(default='', editable=False, max_length='12000'),
        ),
    ]
