# Generated by Django 4.1.1 on 2022-10-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0046_alter_story_content_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content_html',
            field=models.TextField(default='', max_length=12000),
        ),
        migrations.AlterField(
            model_name='story',
            name='content_minified',
            field=models.CharField(default='', max_length=12000),
        ),
    ]
