# Generated by Django 4.1.1 on 2022-10-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0047_alter_story_content_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content_html',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='content_minified',
            field=models.CharField(default='', editable=False, max_length=12000),
        ),
    ]
