# Generated by Django 4.1.1 on 2022-10-25 15:40

from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0049_alter_story_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=django_bleach.models.BleachField(default='Tell your story.', max_length=15000),
        ),
        migrations.AlterField(
            model_name='story',
            name='content_html',
            field=models.TextField(default='', editable=False, max_length=15000),
        ),
        migrations.AlterField(
            model_name='story',
            name='content_minified',
            field=models.CharField(default='', editable=False, max_length=15000),
        ),
    ]
