# Generated by Django 4.0.3 on 2022-09-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_app', '0004_follow_unique_follow_alter_follow_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='about_user',
            field=models.CharField(default='About author', max_length=300),
        ),
    ]
