# Generated by Django 4.0.3 on 2022-09-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_app', '0005_userextra_about_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userextra',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_profile'),
        ),
        migrations.AlterModelTable(
            name='userextra',
            table='user_extra',
        ),
    ]
