# Generated by Django 4.0.3 on 2022-09-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0017_alter_storylist_options_storylist_slug'),
        ('author_app', '0007_userextra_followers_userextra_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='stories',
            field=models.ManyToManyField(to='story_app.story'),
        ),
    ]
