# Generated by Django 4.0.3 on 2022-09-08 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0019_alter_editsuggestion_story_id_alter_likedstory_story_and_more'),
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('author_app', '0014_alter_userextra_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='following',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='following_tags',
            field=models.ManyToManyField(to='taggit.tag'),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='stories',
            field=models.ManyToManyField(to='story_app.story'),
        ),
    ]
