# Generated by Django 4.0.3 on 2022-09-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_app', '0020_alter_userextra_followers_alter_userextra_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='following_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
