# Generated by Django 4.0.3 on 2022-09-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author_app', '0022_userextra_pinned_lists_alter_userextra_lists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextra',
            old_name='following_tags',
            new_name='tags',
        ),
    ]
