# Generated by Django 4.0.3 on 2022-09-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_app', '0023_rename_following_tags_userextra_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='about_user',
            field=models.TextField(default='About author', max_length=300),
        ),
    ]
