# Generated by Django 4.0.3 on 2022-09-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_app', '0028_alter_userextra_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='cover_image',
            field=models.ImageField(default='author_images/profile-default.jpg', upload_to='author_images'),
        ),
    ]
